#!/usr/bin/env node
// scripts/setup-wizard/server.js
// Web-based setup wizard with OAuth callbacks and credential validation.
// Uses only built-in Node.js modules — no Express or other dependencies.

import { createServer } from 'http';
import { readFileSync, existsSync, writeFileSync } from 'fs';
import { join, dirname, extname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { arch } from 'os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const PUBLIC_DIR = join(__dirname, 'public');
const ENV_PATH = join(ROOT, '.env');
const PORT = 3456;

// ── MIME types ──

const MIME = {
  '.html': 'text/html',
  '.css': 'text/css',
  '.js': 'application/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
};

// ── Helpers ──

function loadExistingEnv() {
  if (!existsSync(ENV_PATH)) return {};
  const env = {};
  for (const line of readFileSync(ENV_PATH, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq > 0) env[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
  }
  return env;
}

function detectPuppeteerPath() {
  const cpuArch = arch();
  if (cpuArch === 'arm64' || cpuArch === 'arm') {
    for (const p of ['/usr/bin/chromium-browser', '/usr/bin/chromium', '/snap/bin/chromium']) {
      if (existsSync(p)) return p;
    }
    return '/usr/bin/chromium-browser';
  }
  return '';
}

function defaultExpiryDate() {
  const d = new Date();
  d.setDate(d.getDate() + 60);
  return d.toISOString().split('T')[0];
}

function writeEnvFile(values) {
  const puppeteerPath = detectPuppeteerPath();
  if (puppeteerPath) values.PUPPETEER_EXECUTABLE_PATH = puppeteerPath;

  const lines = [
    '# ═══════════════════════════════════════════════',
    '# LCS Social Media Automation — Environment Config',
    '# Generated by setup wizard',
    '# ═══════════════════════════════════════════════',
    '',
    '# ── Content Generation ──',
    `GEMINI_API_KEY=${values.GEMINI_API_KEY || ''}`,
    '',
    '# ── LinkedIn ──',
    `LINKEDIN_ACCESS_TOKEN=${values.LINKEDIN_ACCESS_TOKEN || ''}`,
    `LINKEDIN_ORG_ID=${values.LINKEDIN_ORG_ID || ''}`,
    `LINKEDIN_CLIENT_ID=${values.LINKEDIN_CLIENT_ID || ''}`,
    `LINKEDIN_CLIENT_SECRET=${values.LINKEDIN_CLIENT_SECRET || ''}`,
    `LINKEDIN_REFRESH_TOKEN=${values.LINKEDIN_REFRESH_TOKEN || ''}`,
    '',
    '# ── Meta (Facebook + Instagram) ──',
    `FB_PAGE_ACCESS_TOKEN=${values.FB_PAGE_ACCESS_TOKEN || ''}`,
    `FB_PAGE_ID=${values.FB_PAGE_ID || ''}`,
    `IG_USER_ID=${values.IG_USER_ID || ''}`,
    `META_APP_ID=${values.META_APP_ID || ''}`,
    `META_APP_SECRET=${values.META_APP_SECRET || ''}`,
    '',
    '# ── Image Hosting ──',
    `IMGBB_API_KEY=${values.IMGBB_API_KEY || ''}`,
    '',
    '# ── Token Expiry Dates ──',
    `TOKEN_EXPIRY_LINKEDIN=${values.TOKEN_EXPIRY_LINKEDIN || ''}`,
    `TOKEN_EXPIRY_META=${values.TOKEN_EXPIRY_META || ''}`,
    '',
    '# ── Telegram Bot ──',
    `TELEGRAM_BOT_TOKEN=${values.TELEGRAM_BOT_TOKEN || ''}`,
    `TELEGRAM_CHAT_ID=${values.TELEGRAM_CHAT_ID || ''}`,
  ];

  if (values.PUPPETEER_EXECUTABLE_PATH) {
    lines.push('', '# ── Puppeteer (ARM) ──');
    lines.push(`PUPPETEER_EXECUTABLE_PATH=${values.PUPPETEER_EXECUTABLE_PATH}`);
  }

  writeFileSync(ENV_PATH, lines.join('\n') + '\n');
}

function sendJson(res, status, data) {
  res.writeHead(status, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify(data));
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => {
      try {
        resolve(JSON.parse(Buffer.concat(chunks).toString()));
      } catch {
        reject(new Error('Invalid JSON'));
      }
    });
    req.on('error', reject);
  });
}

function openBrowser(url) {
  try {
    const platform = process.platform;
    if (platform === 'darwin') execSync(`open "${url}"`, { stdio: 'ignore' });
    else if (platform === 'win32') execSync(`start "" "${url}"`, { stdio: 'ignore' });
    else execSync(`xdg-open "${url}" 2>/dev/null || true`, { stdio: 'ignore' });
  } catch { /* ignore */ }
}

// ── Validation endpoints ──

async function validateTelegram(token) {
  const res = await fetch(`https://api.telegram.org/bot${token}/getMe`);
  const data = await res.json();
  if (!data.ok) throw new Error(data.description || 'Invalid token');
  return { botName: data.result.username };
}

async function validateGemini(key) {
  const res = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models?key=${key}`
  );
  if (!res.ok) throw new Error('Invalid API key');
  return { valid: true };
}

async function validateImgbb(key) {
  // Create a tiny 1x1 red PNG for testing
  const pixel = Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==',
    'base64'
  );
  const form = new FormData();
  form.append('key', key);
  form.append('image', pixel.toString('base64'));
  const res = await fetch('https://api.imgbb.com/1/upload', { method: 'POST', body: form });
  const data = await res.json();
  if (!data.success) throw new Error(data.error?.message || 'Invalid API key');
  return { valid: true };
}

async function validateLinkedIn(token, orgId) {
  const res = await fetch('https://api.linkedin.com/v2/me', {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) throw new Error('Invalid token or insufficient permissions');
  const me = await res.json();

  if (orgId) {
    const orgRes = await fetch(
      `https://api.linkedin.com/rest/organizations/${orgId.replace('urn:li:organization:', '')}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          'LinkedIn-Version': '202602',
        },
      }
    );
    if (!orgRes.ok) throw new Error('Cannot access this organization — check admin permissions');
  }

  return { name: `${me.localizedFirstName} ${me.localizedLastName}` };
}

async function validateMeta(token, pageId) {
  const res = await fetch(
    `https://graph.facebook.com/v25.0/${pageId || 'me'}?fields=name,id&access_token=${token}`
  );
  const data = await res.json();
  if (data.error) throw new Error(data.error.message);
  return { name: data.name, id: data.id };
}

// ── LinkedIn OAuth ──

function linkedInAuthUrl(clientId) {
  const redirect = `http://localhost:${PORT}/callback/linkedin`;
  const scopes = 'w_member_social w_organization_social r_organization_social';
  return (
    `https://www.linkedin.com/oauth/v2/authorization` +
    `?response_type=code` +
    `&client_id=${encodeURIComponent(clientId)}` +
    `&redirect_uri=${encodeURIComponent(redirect)}` +
    `&scope=${encodeURIComponent(scopes)}` +
    `&state=lcs_setup`
  );
}

async function exchangeLinkedInCode(code, clientId, clientSecret) {
  const redirect = `http://localhost:${PORT}/callback/linkedin`;
  const body = new URLSearchParams({
    grant_type: 'authorization_code',
    code,
    redirect_uri: redirect,
    client_id: clientId,
    client_secret: clientSecret,
  });

  const res = await fetch('https://www.linkedin.com/oauth/v2/accessToken', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body,
  });

  const data = await res.json();
  if (data.error) throw new Error(data.error_description || data.error);

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token || '',
    expiresIn: data.expires_in,
  };
}

async function fetchLinkedInOrgs(token) {
  const res = await fetch(
    'https://api.linkedin.com/rest/organizationAcls?q=roleAssignee&role=ADMINISTRATOR',
    {
      headers: {
        Authorization: `Bearer ${token}`,
        'LinkedIn-Version': '202602',
      },
    }
  );
  if (!res.ok) return [];
  const data = await res.json();

  const orgs = [];
  for (const element of data.elements || []) {
    const orgUrn = element.organization;
    if (!orgUrn) continue;
    const orgId = orgUrn.replace('urn:li:organization:', '');
    try {
      const orgRes = await fetch(
        `https://api.linkedin.com/rest/organizations/${orgId}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
            'LinkedIn-Version': '202602',
          },
        }
      );
      if (orgRes.ok) {
        const orgData = await orgRes.json();
        orgs.push({
          urn: orgUrn,
          name: orgData.localizedName || `Organization ${orgId}`,
        });
      }
    } catch { /* skip */ }
  }
  return orgs;
}

// ── Meta OAuth ──

function metaAuthUrl(appId) {
  const redirect = `http://localhost:${PORT}/callback/meta`;
  const scopes = 'pages_manage_posts,instagram_basic,instagram_content_publish,pages_read_engagement';
  return (
    `https://www.facebook.com/v25.0/dialog/oauth` +
    `?client_id=${encodeURIComponent(appId)}` +
    `&redirect_uri=${encodeURIComponent(redirect)}` +
    `&scope=${encodeURIComponent(scopes)}` +
    `&state=lcs_setup`
  );
}

async function exchangeMetaCode(code, appId, appSecret) {
  const redirect = `http://localhost:${PORT}/callback/meta`;
  const url =
    `https://graph.facebook.com/v25.0/oauth/access_token` +
    `?client_id=${encodeURIComponent(appId)}` +
    `&redirect_uri=${encodeURIComponent(redirect)}` +
    `&client_secret=${encodeURIComponent(appSecret)}` +
    `&code=${encodeURIComponent(code)}`;

  const res = await fetch(url);
  const data = await res.json();
  if (data.error) throw new Error(data.error.message);

  // Exchange for long-lived token
  const llUrl =
    `https://graph.facebook.com/v25.0/oauth/access_token` +
    `?grant_type=fb_exchange_token` +
    `&client_id=${encodeURIComponent(appId)}` +
    `&client_secret=${encodeURIComponent(appSecret)}` +
    `&fb_exchange_token=${encodeURIComponent(data.access_token)}`;

  const llRes = await fetch(llUrl);
  const llData = await llRes.json();
  if (llData.error) throw new Error(llData.error.message);

  return {
    userToken: llData.access_token,
    expiresIn: llData.expires_in,
  };
}

async function fetchMetaPages(userToken) {
  const res = await fetch(
    `https://graph.facebook.com/v25.0/me/accounts?access_token=${userToken}`
  );
  const data = await res.json();
  if (data.error) throw new Error(data.error.message);

  const pages = [];
  for (const page of data.data || []) {
    // Check for Instagram business account
    const igRes = await fetch(
      `https://graph.facebook.com/v25.0/${page.id}?fields=instagram_business_account&access_token=${page.access_token}`
    );
    const igData = await igRes.json();
    pages.push({
      id: page.id,
      name: page.name,
      accessToken: page.access_token,
      igUserId: igData.instagram_business_account?.id || null,
    });
  }
  return pages;
}

// ── In-memory state for OAuth flows ──

const oauthState = {
  linkedin: { clientId: '', clientSecret: '' },
  meta: { appId: '', appSecret: '' },
};

// ── HTTP Server ──

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const method = req.method;

  try {
    // ── Static files ──
    if (method === 'GET' && (url.pathname === '/' || url.pathname === '/index.html')) {
      const html = readFileSync(join(PUBLIC_DIR, 'index.html'), 'utf8');
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(html);
      return;
    }

    if (method === 'GET' && url.pathname.startsWith('/public/')) {
      const filePath = join(PUBLIC_DIR, url.pathname.slice(8));
      if (existsSync(filePath)) {
        const ext = extname(filePath);
        res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
        res.end(readFileSync(filePath));
        return;
      }
    }

    // ── API: get current status ──
    if (method === 'GET' && url.pathname === '/api/status') {
      const env = loadExistingEnv();
      sendJson(res, 200, {
        existing: Object.keys(env).length > 0,
        values: {
          TELEGRAM_BOT_TOKEN: env.TELEGRAM_BOT_TOKEN ? '***set***' : '',
          TELEGRAM_CHAT_ID: env.TELEGRAM_CHAT_ID || '',
          GEMINI_API_KEY: env.GEMINI_API_KEY ? '***set***' : '',
          IMGBB_API_KEY: env.IMGBB_API_KEY ? '***set***' : '',
          LINKEDIN_ACCESS_TOKEN: env.LINKEDIN_ACCESS_TOKEN ? '***set***' : '',
          LINKEDIN_ORG_ID: env.LINKEDIN_ORG_ID || '',
          LINKEDIN_CLIENT_ID: env.LINKEDIN_CLIENT_ID || '',
          LINKEDIN_CLIENT_SECRET: env.LINKEDIN_CLIENT_SECRET ? '***set***' : '',
          LINKEDIN_REFRESH_TOKEN: env.LINKEDIN_REFRESH_TOKEN ? '***set***' : '',
          FB_PAGE_ACCESS_TOKEN: env.FB_PAGE_ACCESS_TOKEN ? '***set***' : '',
          FB_PAGE_ID: env.FB_PAGE_ID || '',
          IG_USER_ID: env.IG_USER_ID || '',
          META_APP_ID: env.META_APP_ID || '',
          META_APP_SECRET: env.META_APP_SECRET ? '***set***' : '',
          TOKEN_EXPIRY_LINKEDIN: env.TOKEN_EXPIRY_LINKEDIN || '',
          TOKEN_EXPIRY_META: env.TOKEN_EXPIRY_META || '',
        },
      });
      return;
    }

    // ── API: validate credentials ──
    if (method === 'POST' && url.pathname === '/api/validate') {
      const body = await readBody(req);
      const { type } = body;

      let result;
      switch (type) {
        case 'telegram':
          result = await validateTelegram(body.token);
          break;
        case 'gemini':
          result = await validateGemini(body.key);
          break;
        case 'imgbb':
          result = await validateImgbb(body.key);
          break;
        case 'linkedin':
          result = await validateLinkedIn(body.token, body.orgId);
          break;
        case 'meta':
          result = await validateMeta(body.token, body.pageId);
          break;
        default:
          sendJson(res, 400, { error: 'Unknown validation type' });
          return;
      }

      sendJson(res, 200, { valid: true, ...result });
      return;
    }

    // ── API: save .env ──
    if (method === 'POST' && url.pathname === '/api/save') {
      const body = await readBody(req);
      const existing = loadExistingEnv();
      const merged = { ...existing, ...body.values };
      writeEnvFile(merged);
      sendJson(res, 200, { saved: true, path: ENV_PATH });
      return;
    }

    // ── OAuth: start LinkedIn ──
    if (method === 'POST' && url.pathname === '/api/auth/linkedin/start') {
      const body = await readBody(req);
      oauthState.linkedin.clientId = body.clientId;
      oauthState.linkedin.clientSecret = body.clientSecret;
      const authUrl = linkedInAuthUrl(body.clientId);
      sendJson(res, 200, { authUrl });
      return;
    }

    // ── OAuth: LinkedIn callback ──
    if (method === 'GET' && url.pathname === '/callback/linkedin') {
      const code = url.searchParams.get('code');
      const error = url.searchParams.get('error');

      if (error || !code) {
        const msg = url.searchParams.get('error_description') || 'Authorization denied';
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(callbackPage('LinkedIn', false, msg));
        return;
      }

      try {
        const tokens = await exchangeLinkedInCode(
          code,
          oauthState.linkedin.clientId,
          oauthState.linkedin.clientSecret
        );

        const orgs = await fetchLinkedInOrgs(tokens.accessToken);

        // Store in memory for the frontend to fetch
        oauthState.linkedin.result = {
          accessToken: tokens.accessToken,
          refreshToken: tokens.refreshToken,
          expiresIn: tokens.expiresIn,
          orgs,
        };

        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(callbackPage('LinkedIn', true, 'Connected! Return to the setup wizard.'));
      } catch (err) {
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(callbackPage('LinkedIn', false, err.message));
      }
      return;
    }

    // ── OAuth: fetch LinkedIn result ──
    if (method === 'GET' && url.pathname === '/api/auth/linkedin/result') {
      if (!oauthState.linkedin.result) {
        sendJson(res, 200, { pending: true });
      } else {
        sendJson(res, 200, oauthState.linkedin.result);
        oauthState.linkedin.result = null;
      }
      return;
    }

    // ── OAuth: start Meta ──
    if (method === 'POST' && url.pathname === '/api/auth/meta/start') {
      const body = await readBody(req);
      oauthState.meta.appId = body.appId;
      oauthState.meta.appSecret = body.appSecret;
      const authUrl = metaAuthUrl(body.appId);
      sendJson(res, 200, { authUrl });
      return;
    }

    // ── OAuth: Meta callback ──
    if (method === 'GET' && url.pathname === '/callback/meta') {
      const code = url.searchParams.get('code');
      const error = url.searchParams.get('error');

      if (error || !code) {
        const msg = url.searchParams.get('error_description') || 'Authorization denied';
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(callbackPage('Meta', false, msg));
        return;
      }

      try {
        const tokens = await exchangeMetaCode(
          code,
          oauthState.meta.appId,
          oauthState.meta.appSecret
        );

        const pages = await fetchMetaPages(tokens.userToken);

        oauthState.meta.result = {
          userToken: tokens.userToken,
          expiresIn: tokens.expiresIn,
          pages,
        };

        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(callbackPage('Meta', true, 'Connected! Return to the setup wizard.'));
      } catch (err) {
        res.writeHead(200, { 'Content-Type': 'text/html' });
        res.end(callbackPage('Meta', false, err.message));
      }
      return;
    }

    // ── OAuth: fetch Meta result ──
    if (method === 'GET' && url.pathname === '/api/auth/meta/result') {
      if (!oauthState.meta.result) {
        sendJson(res, 200, { pending: true });
      } else {
        sendJson(res, 200, oauthState.meta.result);
        oauthState.meta.result = null;
      }
      return;
    }

    // ── 404 ──
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Not found');
  } catch (err) {
    console.error('Server error:', err);
    sendJson(res, 500, { error: err.message });
  }
});

// ── OAuth callback HTML page ──

function callbackPage(platform, success, message) {
  const icon = success ? '&#10003;' : '&#10007;';
  const color = success ? '#22c55e' : '#ef4444';
  return `<!DOCTYPE html>
<html><head><title>${platform} — ${success ? 'Connected' : 'Error'}</title>
<style>
  body { font-family: system-ui, sans-serif; display: flex; justify-content: center;
         align-items: center; min-height: 100vh; margin: 0; background: #f8f9fa; }
  .card { background: white; border-radius: 12px; padding: 48px; text-align: center;
          box-shadow: 0 2px 12px rgba(0,0,0,0.08); max-width: 400px; }
  .icon { font-size: 48px; color: ${color}; margin-bottom: 16px; }
  h2 { margin: 0 0 8px; color: #1a1a2e; }
  p { color: #666; margin: 0; }
</style></head>
<body><div class="card">
  <div class="icon">${icon}</div>
  <h2>${platform} ${success ? 'Connected' : 'Error'}</h2>
  <p>${message}</p>
</div></body></html>`;
}

// ── Start ──

server.listen(PORT, () => {
  const url = `http://localhost:${PORT}`;
  console.log('');
  console.log('╔══════════════════════════════════════════════════╗');
  console.log('║   LCS Social Media — Setup Wizard                ║');
  console.log('╚══════════════════════════════════════════════════╝');
  console.log('');
  console.log(`  Open in your browser: ${url}`);
  console.log('');
  console.log('  Press Ctrl+C to stop the wizard.');
  console.log('');

  openBrowser(url);
});

// Export for reuse by /reauth command
export { server, PORT, writeEnvFile, loadExistingEnv };
